fix junit go install

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -40,6 +40,9 @@ jobs:
       - name: Set release version env
         run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
 
+      - name: Install go-junit-report
+        run: go install github.com/jstemmer/go-junit-report/v2@latest
+
       - name: Run tests and save json report
         run: |
           timestamp=$(date +'%Y%m%d%H%M')
@@ -49,17 +52,20 @@ jobs:
         env:
           SKIP_LINT: 1
 
-      - name: Install go-junit-report
-        run: |
-          go get -u github.com/jstemmer/go-junit-report
-        env:
-          GO111MODULE: on
-
       - name: Convert JSON Report to XML
         run: |
-          filename=$(ls | grep -E '^[0-9]{12}_linodego_test_report\.json') 
-          xml_filename=$(echo "$filename" | sed 's/\.json$/.xml/')
-          go-junit-report < "$filename" > "$xml_filename"
+          filename=$(ls | grep -E '^[0-9]{12}_linodego_test_report\.json')
+
+          if [ -f "$filename" ]; then
+            go_junit_report_dir=$(go env GOPATH)/bin
+            export PATH="$PATH:$go_junit_report_dir"
+            xml_filename=$(echo "$filename" | sed 's/\.json$/.xml/')
+            go-junit-report < "$filename" > "$xml_filename"
+            echo "Conversion from JSON to XML completed successfully."
+          else
+            echo "JSON test report file not found."
+            exit 1
+          fi
         env:
           GO111MODULE: on
 
